local cfg = {}

cfg.items = {
	["suspensaoar"] = { "Suspensão Ar",0.1 },
	["moduloneon"] = { "Módulo Neon",0.1 },
	["moduloxenon"] = { "Módulo Xenon",0.1 },	
	["taurina"] = { "TAURINA",0.1 },
	["cafeina"] = { "CAFEÍNA",0.1 },	
	["combo1"] = { "COMBO STARBUCKS",0.1 },
	["cafe"] = { "CAFÉ STARBUCKS",0.1 },
	["donut"] = { "DONUT",0.1 },
	["sanduiche"] = { "SANDUICHE",0.1 },	
	["ferramenta"] = { "Ferramenta",0.1 },
	["varadepesca"] = { "VARA DE PESCA",0.1 },
	["carteira"] = { "Dinheiro na Carteira", 0.0 },
	["tablet"] = { "Tablet",0.1 },	
	["encomenda"] = { "Encomenda",0.1 },
	["sacodelixo"] = { "Saco de Lixo",0.1 },
	["garrafavazia"] = { "Garrafa Vazia",0.1 },
	["garrafadeleite"] = { "Garrafa de Leite",0.1 },
	["leite"] = { "Leite",0.1 },
	["tora"] = { "Tora de Madeira",0.1 },
	["alianca"] = { "Aliança",0 },
	["bandagem"] = { "Bandagem",0.1 },
	["dorflex"] = { "Dorflex",0 },
	["cicatricure"] = { "Cicatricure",0 },
	["dipiroca"] = { "Dipiroca",0 },
	["nocucedin"] = { "Nocucedin",0 },
	["paracetanal"] = { "Paracetanal",0 },
	["decupramim"] = { "Decupramim",0 },
	["buscopau"] = { "Buscopau",0 },
	["navagina"] = { "Navagina",0 },
	["analdor"] = { "Analdor",0 },
	["sefodex"] = { "Sefodex",0 },
	["nokusin"] = { "Nokusin",0 },
	["glicoanal"] = { "Glicoanal",0 },
	["batata"] = { "Batata",0.1 },
	["cerveja"] = { "Cerveja",0.1 },
	["tequila"] = { "Tequila",0.1 },
	["vodka"] = { "Vodka",0.1 },
	["whisky"] = { "Whisky",0.1 },
	["conhaque"] = { "Conhaque",0.1 },
	["absinto"] = { "Absinto",0.1 },
	["dinheirosujo"] = { "Dinheiro Sujo",0 },
	["dinheirofalso"] = { "Dineiro Sujo",0 },
	["repairkit"] = { "Kit de Reparos",0.1 },
	["algemas"] = { "Algemas",0.1 },
	["capuz"] = { "Capuz",0.1 },
	["lockpick"] = { "Lockpick",10 },
	["masterpick"] = { "Masterpick",10 },
	["pneus"] = { "Pneus", 0.1 },
	["militec"] = { "Militec-1",0.1 },
	["carnedecormorao"] = { "Carne de Cormorão",0.1 },
	["carnedecorvo"] = { "Carne de Corvo",0.1 },
	["carnedeaguia"] = { "Carne de Águia",0.1 },
	["carnedecervo"] = { "Carne de Cervo",0.1 },
	["carnedecoelho"] = { "Carne de Coelho",0.1 },
	["carnedecoyote"] = { "Carne de Coyote",1 },
	["carnedelobo"] = { "Carne de Lobo",0.1 },
	["carnedepuma"] = { "Carne de Puma",0.1 },
	["carnedejavali"] = { "Carne de Javali",0.1 },
	["amora"] = { "Amora",0.1 },
	["cereja"] = { "Cereja",0.1 },
	["isca"] = { "Isca",0.1 },
	["dourado"] = { "Dourado",0.1 },
	["corvina"] = { "Corvina",0.1 },
	["salmao"] = { "Salmão",0.1 },
	["pacu"] = { "Pacu",0.1 },
	["pintado"] = { "Pintado",0.1 },
	["pirarucu"] = { "Pirarucu",0.1 },
	["tilapia"] = { "Tilápia",0.1 },
	["tucunare"] = { "Tucunaré",0.1 },
	["lambari"] = { "Lambari",0.1 },
	["energetico"] = { "Energético",0.1 },
	["mochila"] = { "Mochila",0 },
	["adubo"] = { "Adubo",0.1 },
	["fertilizante"] = { "Fertilizante",0.1 },
------ fome e sede ----
	["refrigerante"] = { "Refrigerante",0.1 },
	["big-mec"] = { "BIG KING",0.1 },
	["mc-cheddar"] = { "MEGA STACKER",0.1 },
	["quarterao"] = { "CHEESEBURGER",0.1 },
	["combo"] = { "COMBO KING",0.1 },
	["x-tudo"] = { "Mata Fome",0.1 }, --

	-- Maconha -----------------------------------------------------------------
	["maconha"] = { "Maconha",0.1 },
	["ramosdemaconha"] = { "Ramos de Maconha",0.1 },
	["maconhanaoprocessada"] = { "Maconha não Processada",0.1 },
	["maconhamisturada"] = { "Maconha Misturada",0.1 },
	["baseado"] = { "Baseado",0.1 },
	["seda"] = { "Papel de Seda",0.1 },
	["receita1"] = { "Receita Médica",0.0 },
	["receita2"] = { "Receita Médica",0.0 },
	----------------------------------------------------------------------------
	["acidobateria"] = { "Ácido de bateria",0.1 },
	["anfetamina"] = { "Anfetamina",0.1 },
	["cristal"] = { "Cristal de Metanfetamina",0.1 },
	["metanfetamina"] = { "Metanfetamina",0.1 },
	["pipe"] = { "Pipe",0.1 },
	-- Ecstasy -----------------------------------------------------------------
	["ocitocina"] = { "Ocitocina Sintética",0.1 },
	["ociacido"] = { "Ácido Anf. Desidratado",0.1 },
	["primaecstasy"] = { "Matéria Prima - Ecstasy",0.1 },
	["ecstasy"] = { "Ecstasy",0.1 },
	["glicerina"] = { "Glicerina",0.1 },
	-- Cocaína -----------------------------------------------------------------
	["folhadecoca"] = { "Folha de Cocaina",0.1 },
	["pastadecoca"] = { "Pasta de Cocaina",0.1 },
	["cocamisturada"] = { "Cocaína Misturada",0.1 },
	["cocaina"] = { "Cocaína",0.1 },
	["ziplock"] = { "Saco ZipLock",0.1 },
	-- FARMS -----------------------------------------------------------------	
	["laranja"] = { "Laranja",0.1 },
	["tomate"] = { "Tomate",0.1 },
	["corpopistol"] = { "Corpo Pistol",0.1 },
	["placa-metal"] = { "Placa de Metal",0.1 },
	["gatilho"] = { "Gatilho",0.1 },
	["molas"] = { "Molas",0.1 },
	["corposub"] = { "Corpo Sub",0.1 },
	["corporifle"] = { "Corpo Rifle",0.1 },
	["amido"] = { "Amido",0.1 },
	["composto"] = { "Composto",0.1 },
	["lsdembalado"] = { "LSD Embalado",0.1 },
	["embalagem"] = { "Embalagem",0.1 },
	["saquinhos"] = { "Saquinhos",0.1 },
	["cocaembalada"] = { "Coca Embalada",0.1 },
	["balanca"] = { "balanca",0.1 },
	["tablete"] = { "tablete",0.1 },
	["notafiscalfalsa"] = { "Nota Fiscal Falsa",0.1 },
	["couro"] = { "couro",0.1 },
	["linha"] = { "linha",0.1 },
	["tesoura"] = { "tesoura",0.1 },
	["aco"] = { "aco",0.1 },
	["aluminio"] = { "aluminio",0.1 },
	["chave"] = { "chave",0.1 },
	["plastico"] = { "plastico",0.1 },
	["cobre"] = { "cobre",0.1 },
	["chip"] = { "chip",0.1 },
	["cordas"] = { "cordas",0.1 },
	["chip"] = { "chip",0.1 },
	["tinta"] = { "tinta",0.1 },
	["co2"] = { "co2",0.1 },
	["nitro"] = { "nitro",0.1 },
	----------------------------------------------------------------------------
	-- Lavagem de Dinheiro -----------------------------------------------------
	["impostoderenda"] = { "Imposto de Renda",0.0 },
	["impostoderendafalso"] = { "Imposto de Renda Falso",0.0 },
    ----------------------------------------------------------------------------
	-- Bratva Munições ---------------------------------------------------------
	["capsula"] = { "Cápsula",0.1 },
	["polvora"] = { "Pólvora",0.1 },
	["detonador"] = { "Detonador",0.1 },
	["ferramentas"] = { "Ferramentas Pesadas",10.00 },
    ----------------------------------------------------------------------------
	["carregador"] = { "Carregador",0.1 },
	["mira"] = { "Mira",0.1 },
	["silenciador"] = { "Silenciador",0.1 },
	["xratao"] = { "X-Ratão",0.1 },
	["celular"] = { "Celular",0.1 },
	["grip"] = { "Grip.png",0.1 },
	["capsula"] = { "Cápsula",0.1 },
	["polvora"] = { "Pólvora",0.1 },
	["orgaos"] = { "Órgãos",0.1 },
	["etiqueta"] = { "Etiqueta",0 },
	["pendrive"] = { "Pendrive",0.1 },
	["relogioroubado"] = { "Relógio Roubado",0.1 },
	["pulseiraroubada"] = { "Pulseira Roubada",0.1 },
	["anelroubado"] = { "Anel Roubado",0.1 },
	["colarroubado"] = { "Colar Roubado",0.1 },
	["brincoroubado"] = { "Brinco Roubado",0.1 },
	["carteiraroubada"] = { "Carteira Roubada",0.1 },
	["tabletroubado"] = { "Tablet Roubado",0.1 },
	["sapatosroubado"] = { "Sapatos Roubado",0.1 },
	["vibradorroubado"] = { "Vibrador Roubado",0.1 },
	["perfumeroubado"] = { "Perfume Roubado",0.1 },
	["fungo"] = { "Fungo",0.1 },
    ["dietilamina"] = { "Dietilamina",0.1 },
    ["lsd"] = { "LSD",0.1 },
	["armacaodearma"] = { "Armacao de Arma",0.1 },
	["pecadearma"] = { "Peça de arma",0.1 },
	["logsinvasao"] = { "Logs de Invasão",0.1 },
	["keysinvasao"] = { "Keys para Invasão",0.1 },
	["pendriveinformacoes"] = { "Pendrive com Informações",0.1 },
	["acessodeepweb"] = { "Acesso á DeepWeb",0.1 },
	["diamante"] = { "Min. Diamante",0.1 },
	["ouro"] = { "Min. Ouro",0.1 },
	["bronze"] = { "Min. Bronze",0.1 },
	["ferro"] = { "Min. Ferro",0.1 },
	["rubi"] = { "Min. Rubi",0.1 },
	["esmeralda"] = { "Min. Esmeralda",0.1 },
	["safira"] = { "Min. Safira",0.1 },
	["topazio"] = { "Min. Topazio",0.1 },
	["ametista"] = { "Min. Ametista",0.1 },
	["diamante2"] = { "Diamante",0.1 },
	["ouro2"] = { "Ouro",0.1 },
	["bronze2"] = { "Bronze",0.1 },
	["ferro2"] = { "Ferro",0.1 },
	["rubi2"] = { "Rubi",0.1 },
	["esmeralda2"] = { "Esmeralda",0.1 },
	["safira2"] = { "Safira",0.1 },
	["topazio2"] = { "Topazio",0.1 },
	["ametista2"] = { "Ametista",0.1 },
	["ingresso"] = { "Ingresso",0.1 },
	["radio"] = { "Radio",0.1 },
	["serra"] = { "Serra",0.1 },
	["furadeira"] = { "Furadeira",0.1 },
	["c4"] = { "C-4",0.1 },
	["roupas"] = { "Roupas",2.0 },
	["graos"] = { "Graos",0.1 },
	["graosimpuros"] = { "Graos Impuros",0.1 },
	["xerelto"] = { "Xerelto",0.1 },
  	["coumadin"] = { "Coumadin",0.1 },
	["identidade"] = { "Identidade",0 },
	["keycard"] = { "Keycard",0.1 },
	["laranja"] = { "Laranja",0.1 },
	["nitro"] = { "Óxido Nitroso",0.1 },
	["tartaruga"] = { "Filhote de Tartaruga",0.1 },
	["carnedetartaruga"] = { "Carne de Tartaruga",0.1 },
	["agua"] = { "agua",0.1 },
	["placa"] = { "Placa",0.1 },
	["aneldecompromisso"] = { "Anel de Compromisso",0.1 },
	["colardeperolas"] = { "Colar de Pérolas",0.1 },
	["pulseiradeouro"] = { "Pulseira de Ouro",0.1 },
	["chocolate"] = { "Chocolate",0.1 },
	["pirulito"] = { "Pirulito",0.1 },
	["buque"] = { "Buquê de Flores",0.1 },
	["colete"] = { "Colete Balístico", 0.1},
	["projetoassaultrifle"] = { "Projeto Ak-47", 0.1},
	["projetoassaultsmg"] = { "Projeto MAG-PDR", 0.1},
	["projetobullpuprifle"] = { "Projeto QBZ", 0.1},
	["projetocarbinerifle"] = { "Projeto M4A1", 0.1},
	["projetocombatpdw"] = { "Projeto MPX", 0.1},
	["projetocombatpistol"] = { "Projeto Glock 19", 0.1},
	["projetogusenberg"] = { "Projeto Thompson", 0.1},
	["projetopistol"] = { "Projeto Fiven", 0.1},
	["projetopumpshotgun"] = { "Projeto Shotgun", 0.1},
	["projetosawnoffshotgun"] = { "Projeto Shot Cano Serrado", 0.1},
	["projetosmg"] = { "Projeto MP5", 0.1},
	-- Comidas
	["water"] = { "Garrafa de Água",0.1 },
	["hamburger"] = { "Hamburger",0.1 },	
	["lanche"] = { "Lanche",0.1 },
	["maquineta"] = { "Maquina de Cartão",0.1 },
	["cartao"] = { "Cartão Débito",0.1 }
}

local function load_item_pack(name)
	local items = module("cfg/item/"..name)
	if items then
		for k,v in pairs(items) do
			cfg.items[k] = v
		end
	end
end

load_item_pack("armamentos")

return cfg